### ISSUE TITLE
TypeError: Cannot read property 'UI' of undefined

### ISSUE THREAD

**Issue by trekvr** [grtjn/ml-lodlive-ng#11]
Hi,

I'm getting below error while working on this

```
Error:
TypeError: Cannot read property 'UI' of undefined
```

Attached the html template for the same: [sample3.zip](https://github.com/grtjn/ml-lodlive-ng/files/449739/sample3.zip)

Kindly let me know how to fix this, I'm new to angular js, just want to show data from MarkLogic if the dbpedia endpoint works.

Thanks,
Rajesh

**Comment by grtjn** [comment]
Hmm, the documentation assumes ctrl is injected in $scope. We typically arrange that in angular routing, but you can fake it by adding this line to your controller:

```
  $scope.ctrl = ctrl;
```

After that, it should work..

**Comment by grtjn** [comment]
You can confirm it worked by closing this ticket.. (or leave a comment if it didn't of course..)

**Comment by trekvr** [comment]
Thanks for replying.. where do I need to do this change? In html attached or the js file? Can you please let me know.

**Comment by trekvr** [comment]
I'm not in front of my system.. will test this and reply back... Once again thank you for your help 😀

**Comment by grtjn** [comment]
Your sample3.html has a script tag in which you declare the main controller. In there, you can replace this (line 17):

```
  var ctrl = this;
```

with:

```
  var ctrl = this;
  $scope.ctrl = ctrl;
```

**Comment by trekvr** [comment]
Thanks and the change is working. Now i can show my MarkLogic semantic content in relationship model.

-Rajesh
