### ISSUE TITLE
update ml-lodlive dependency

### ISSUE THREAD

**Issue by joemfb** [grtjn/ml-lodlive-ng#5]
An updated version of `ml-lodlive` has been released (`0.4.0`). Please update bower.json to reference this version, as it has many fixes and improvements.

Note: for the purposes of this component, this release is mostly backwards compatible.

**Comment by grtjn** [comment]
Did you by any chance run a test were you installed this together with ml-lodlive#0.4.0 to see how well that works?

**Comment by grtjn** [comment]
I have added you as collaborator. Feel free to open a PR and/or mess about.. ;)
